# Generated by Django 2.2.1 on 2019-05-29 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=250)),
                ('Description', models.TextField(max_length=10000)),
                ('Status', models.CharField(choices=[('To-Do', 'To-Do'), ('Doing', 'Doing'), ('Completed', 'Completed'), ('QA', 'QA'), ('Closed', 'Closed'), ('New', 'New')], default='New', max_length=7)),
            ],
        ),
    ]
