# Generated by Django 2.2.1 on 2019-05-25 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=250)),
                ('Description', models.TextField(max_length=10000)),
                ('Status', models.CharField(default='New', max_length=7)),
            ],
        ),
    ]
