# Generated by Django 2.2.1 on 2019-05-25 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='Status',
            field=models.CharField(choices=[('To-Do', 'To-Do'), ('Doing', 'Doing'), ('Completed', 'Completed'), ('QA', 'QA'), ('Closed', 'Closed'), ('New', 'New')], default='New', max_length=7),
        ),
    ]
